name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Find root package.json and install dependencies
        run: |
          PROJECT_DIR=$(dirname $(find . -name 'package.json' -not -path '*/node_modules/*' -print -quit))
          echo "Found package.json at $PROJECT_DIR"
          cd $PROJECT_DIR
          npm install

      - name: Run tests
        run: |
          PROJECT_DIR=$(dirname $(find . -name 'package.json' -not -path '*/node_modules/*' -print -quit))
          echo "Found package.json at $PROJECT_DIR"
          cd $PROJECT_DIR
          npm test
