name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: node12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd r-parser  # Переход в подкаталог нового проекта
          npm install

      - name: Run tests
        run: |
          cd r-parser  # Переход в подкаталог нового проекта
          npm test
