name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Find r-parser folder and install dependencies
        run: |
          PROJECT_DIR=$(find . -type d -name 'parser' -print -quit)
          echo "Found r-parser at $PROJECT_DIR"
          cd $PROJECT_DIR
          npm install

      - name: Run tests
        run: |
          PROJECT_DIR=$(find . -type d -name 'parser' -print -quit)
          echo "Found r-parser at $PROJECT_DIR"
          cd $PROJECT_DIR
          npm test
