name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Navigate to project root and install dependencies
        run: |
          cd ../..
          echo "Moved to project root: $(pwd)"
          npm install

      - name: Run tests
        run: |
          cd ../..
          echo "Moved to project root: $(pwd)"
          npm test
